### ISSUE TITLE
Add CSI index support

### ISSUE THREAD

**Issue by diego-rt** [cmdcolin/jbrowse-plugin-mafviewer#10]
Hello,

First of all many thanks for the amazing plugin. It's so exciting to use and makes browsing genome alignments such as breeze!

I was wondering whether it would be possible to implement support for CSI indexes? My genome has very large chromosomes (512M < X < 2GB) and therefore needs CSI indexes to work. This mean that in tabix I need to use the following command:

```
tabix -C reference.out.bed.gz
```

However, when I attempt to load the MAF file with this index I get the following error:

```
Error: Not a TBI file

    at x._parse (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/8120.38037f51.chunk.js:1:5301)
    at async x.getMetadata (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/8120.38037f51.chunk.js:1:4665)
    at async S.getReferenceSequenceNames (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/8120.38037f51.chunk.js:1:13479)
```

I'm not sure if this is something that should be addressed by your plugin or by jbrowse, but feel free to let me know and I can pull an issue there.

Many thanks!

**Comment by cmdcolin** [comment]
thanks for reporting. I made a new release of the plugin that now allows you to specify the "index type" when you are inputting MAF tabix files

the file importer looks like this

![image](https://github.com/user-attachments/assets/4f0a200a-3838-4cda-b283-9805359cc910)


I try to avoid auto-inferring since files can sometimes come without file extensions, etc.

I am trying to do a couple other updates to this plugin so if you have any more ideas/input let me know...

**Comment by diego-rt** [comment]
Thank you so much for the insanely fast fix! I can confirm it works now.

Sure thing, if I think of anything I'll let you know.

In the case of cactus-derived MAFs, it would be neat to be able to input the Newick tree used for the alignment and have it figure out the species list on its own. Maybe with the tree shown to the side or something. And perhaps with the ability to toggle displaying the ancestral genomes (i.e. internal nodes listed in the Newick tree). 

But overall, great plugin and thanks so much for having developed it!

**Comment by diego-rt** [comment]
Another thing would be that when you have loads of rows it becomes hard to tell at which row you are looking at. 

It would be nice to be able to toggle some sort of crosshairs like in the bigwig track, which when highlighted gives you info on the species or etc. It doesn't necessarily have to give you the info on a pop up, it might be enough to just make an horizontal line appear that lets you track at which species name you are looking at (again, like in the bigwig tracks).

**Comment by diego-rt** [comment]
Sorry one more thing! 

It would also be nice to be able to "right click -> copy" the sequence of a specific species. Ideally not the entire alignment block but some kind of dragging selection like when copying the reference genome sequence.

**Comment by cmdcolin** [comment]
random update:

I did some of these updates awhile ago but just released

- added a new crosshair feature along with beta TAF file support
- added a newick tree feature
 
still cant display the ancestral (even though i can see that some cactus have ancestral, it just shows the leaf nodes),  but I'll brainstorm that, my PI was also interested in this

**Comment by cmdcolin** [comment]
might b able to close for now, but feel free to let me know if you have any more ideas!

**Comment by diego-rt** [comment]
Oh cool!!! Thank you so much @cmdcolin , really appreciated! 

However, I'm trying to try the updates out but jbrowse seems to be crashing on me when I load the MAF file (bed format). I'm also not able to click on the csi button anymore (but it accepts the csi file) so maybe it is linked to that?

**Comment by diego-rt** [comment]
Hi @cmdcolin 

So after the update it no longer crashed and I could test out the tree feature, which is super cool! Browsing cactus alignments is so much more informative and intuitive now, so thanks so much!

The crosshairs is also super useful, and the little tip with the species name as well, so thanks again!

The only thing that I'm having some trouble with is that somehow not all the alignments are being shown. I was using the same file with the previous version so I know the file is not the problem. I'm using the MafTabixAdapter with CSI index. When I import the species list from the tree, only the reference genome is shown. When I import the species list manually, only the ancestor nodes and the reference species are shown (I listed the ancestral nodes in the species list). All the inputs are identical to the ones I used to use before.

![Image](https://github.com/user-attachments/assets/b9b27826-da1b-48a9-8dc1-2bcadac3522e)

But other than that, thanks so much for the new features and the amazing plugin!

P.S. I just realized that maybe being able to toggle the crosshairs on/off as an option might be useful i.e. when taking screenshots like above.

**Comment by cmdcolin** [comment]
do you have your config.json and a sample of the maf file? I might be able to reproduce even if not, but might just get me wired in

there is a thing where various sample names e.g. from the tree file or the samples list in the config have to match exactly the names in the maf file and it might be more picky about that after latest update or a bug/regression appeared

**Comment by diego-rt** [comment]
Sure thing, here go both. Thanks for the speedy reply!

[250120_Cactus.jbrowse.json](https://github.com/user-attachments/files/18659418/250120_Cactus.jbrowse.json)
[MAF.sample.txt](https://github.com/user-attachments/files/18659419/MAF.sample.txt)

**Comment by diego-rt** [comment]
Yeah I was also wondering whether it might have something to do with dots or underscores in the species or chromosome names since the ancestor nodes don't have them and work

**Comment by cmdcolin** [comment]
yes this appears related to having 'multiple dots' in the name


If i make this change

```
diff --git a/src/MafTabixAdapter/MafTabixAdapter.ts b/src/MafTabixAdapter/MafTabixAdapter.ts
index 3a7755e..d447984 100644
--- a/src/MafTabixAdapter/MafTabixAdapter.ts
+++ b/src/MafTabixAdapter/MafTabixAdapter.ts
@@ -67,7 +67,8 @@ export default class MafTabixAdapter extends BaseFeatureDataAdapter {

         for (const [j, elt] of data.entries()) {
           const ad = elt.split(':')
-          const idx = ad[0]!.lastIndexOf('.') // organism name is everything before last dot
+          const idx = ad[0]!.indexOf('.') // organism name is everything before first dot
           const org = ad[0]!.slice(0, idx)
```

then your file shows up

![Image](https://github.com/user-attachments/assets/b0def7bb-038f-4789-8362-943a6d2f2b2f)

i am trying to think what the best proper fix is. it could be made "configurable" whether to choose first or last, but i would like a good default behavior. 

My best genral general recommendation would be to try to avoid dots in the refnames and assembly names if possible! I had previously mad it "lastIndexOf" in response to another user who had assembly names with "." (they had SAMPLE1.1 and SAMPLE1.2 for the different haplotypes) but your situation appars a bit reversed where there is extra information in the middle that is not part of the assembly name (??)

this is something that is really just sort of problematic about the MAF format, and mentioned here https://github.com/ComparativeGenomicsToolkit/taffy/issues/71

i would like it if taf format solved this by separating refnames and assemblynames like that issue mentions!

**Comment by diego-rt** [comment]
Oh I see! Yeah in my case the dots come from the NCBI accession names for each chromosome, which I think would be the most common input for these kind of alignments? Yes I also have some extra information after than indicating the coordinates (since I am typically taking a specific region for the alignment) but since it is after the dot I assumed it would not interfere and would be considered part of the chromosome name. 

My understanding is that the typical file would contain something along the lines of `${species}.${sequenceName}:etc:etc:etc` such as for example : `Branchiostoma_belcheri.JALCYT010000035.1:275:32:+:2960354:CATCAAGC [...]`

And I totally agree that the use of the dot as separator is ridiculous!

**Comment by cmdcolin** [comment]
ya, NCBI refnames are a good example of the dots being in the refname...

released a new version with a "heuristic" that tries tohelp in the general case


it splits by '.'

if the second field is a number, and it there ar greater than 3 fields split by dot, it joins the first two as assembly name

otherwise it matches basically what you have

you would not want to combine dots in refname AND assemblyname with this heuristic :)
